
install:
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman --noconfirm -Sy
  - pacman --noconfirm --needed -S pacman-mirrors
  - pacman --noconfirm -Sy
  - pacman --noconfirm --needed -S base-devel git zip mingw-w64-x86_64-toolchain

build: off

test_script:
  - set
  - env
