
install:
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman --noconfirm -Sy
  - pacman --noconfirm --needed -S pacman-mirrors
  - pacman --noconfirm -Sy
  - pacman --noconfirm --needed -S base-devel git zip mingw-w64-x86_64-toolchain
  - ps: >-
      bash -c @"
        exec 0</dev/null 2>&1
        set -x
        git clone https://github.com/kiwiroy/openssl.git
      "@

build_script:
    - ps: >-
        bash -c @"
          # stdin seems to be invalid on appveyor, so set it to null
          exec 0</dev/null 2>&1
          set -x
          ./config shared zlib enable-static-engine enable-rfc3779
          make
        "@

test_script:
  - set
  - env
